Feature/381 bug zero moving casecount
mathematica-mpr/covid_risk_score pull request #123
Opened 2022-05-10 19:56 UTC by pendlrobinson

Link to Jira Ticket: https://mathematicampr.atlassian.net/browse/C19ANDME-381

2022-05-10 22:03 UTC, xindyhu requested changes

2022-05-10 22:03 UTC, xindyhu commented on app/functions.R
> +                           For more information, please check the ", tags$a("USAFacts", href = urls$usafacts_data), " or state agency's health department website.",
A minor typo. "fr the county" should be "for the county".

2022-05-11 12:32 UTC, pendlrobinson commented on app/functions.R
> +                           For more information, please check the ", tags$a("USAFacts", href = urls$usafacts_data), " or state agency's health department website.",
Thank you for catching the typo. I corrected the text.

2022-05-13 17:33 UTC, xindyhu approved these changes

2022-05-13 17:33 UTC, merged

2022-05-13 17:33 UTC, xindyhu commented
@pendlrobinson  Do you think this is worth reflecting in the changelog?

2022-05-13 17:53 UTC, pendlrobinson commented
> @pendlrobinson Do you think this is worth reflecting in the changelog?

@xindyhu , good idea. I created a PR to document this update to the changelog.  Link to PR: https://github.com/mathematica-mpr/math-api-covid-risk-calculator/pull/201

2022-05-13 20:41 UTC, xindyhu commented
> > @pendlrobinson Do you think this is worth reflecting in the changelog?
> 
> @xindyhu , good idea. I created a PR to document this update to the changelog. Link to PR: [mathematica-mpr/math-api-covid-risk-calculator#201](https://github.com/mathematica-mpr/math-api-covid-risk-calculator/pull/201)

Thank you @pendlrobinson , the PR looks good!