Feature/fix icu prob
mathematica-mpr/covid_risk_score pull request #43
Opened 2020-09-17 06:20 UTC by xindyhu

Hi Jennifer,
I implemented your idea of conditional probability for ICU risk. Please take a look. 
I also updated the documentation because as you know some of the information was outdated.
Thank you!
close #42

2020-09-17 17:59 UTC, jestarling approved these changes

2020-09-18 01:50 UTC, xindyhu commented
@jestarling Please take a look at the small update I made to the UI. Because we don't have aOR for "immune" and "other", I made it more explicit in the UI by unselecting other options once any of these two is selected.

2020-09-18 13:41 UTC, jestarling requested changes
Some very minor comments:

1. In the user messages, change "select" to "selecting", and selections-->conditions to avoid using "select" so many times in one sentence:  (select**ing** this will unselect other **conditions** due to lack of mutually adjusted odds ratios)
2. What do we want a user to do if they are say immunocompromised and have some other condition?  Should they check the other conditions, or stick with immunocompromised?  It might be good to add some messaging to guide a user with complex medical history.

2020-09-18 22:02 UTC, jestarling approved these changes

2020-09-18 23:42 UTC, merged